CREATE TABLE IF NOT EXISTS leads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  score INTEGER NOT NULL,
  plan TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
